# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
fr:
  languageCode: fr-fr
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/fr

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
  menus:
    main:
      - name: Home
        url: en/
        weight: 10
      - name: Papers
        url: publications/
        weight: 11
      - name: Talks
        url: talks/
        weight: 12
      - name: Experience
        url: experience/
        weight: 13
      - name: Projects
        url: projects/
        weight: 14
      - name: Teaching
        url: teaching/
        weight: 15
